[xnvme.repository]
upstream = "https://github.com/OpenMPDK/xNVMe.git"
path = "/root/git/xnvme"

[xnvme.source]
path = "/tmp/xnvme_source"

[[devices]]
uri = "2GB"
nsid = 1
labels = [ "dev", "bdev", "nvm", "ramdisk" ]
driver_attachment = "kernel"

[fio]
bin = "/opt/fio/bin/fio"

[fio.repository]
upstream = "https://github.com/axboe/fio.git"
path = "/root/git/fio"
tag = "fio-3.34"

[fio.build]
prefix = "/opt/fio"

[fio.engines.libaio]
type = "builtin"

[fio.engines.io_uring]
type = "builtin"

[fio.engines.io_uring_cmd]
type = "builtin"

[fio.engines.xnvme]
type = "builtin"

[fio.engines.spdk_nvme]
path = "/opt/aux/spdk_nvme"
type = "external_preload"

[fio.engines.spdk_bdev]
path = "/opt/aux/spdk_bdev"
type = "external_preload"
